name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: jhonzito66
          outputs: |
            dist/github-contribution-grid-snake.svg
          snake_color: "F97316"

      - uses: Platane/snk/output@v3
        with:
          dist: dist
